server:
  port: ${PORT:0}
  
spring:
  application:
    name: restfulserver

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    instance-id: ${spring.application.name}${random.value}
